# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.6'

volumes:
  pbft-shared:

networks:
  default:
    external:
      name: 'siot_blockchain'

services:

# -------------=== rest api ===-------------

  rest-api-20:
    image: hyperledger/sawtooth-rest-api:nightly
    container_name: sawtooth-rest-api-default-20
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-20:4004 \
          --bind rest-api-20:8008
      "
    stop_signal: SIGKILL

  rest-api-21:
    image: hyperledger/sawtooth-rest-api:nightly
    container_name: sawtooth-rest-api-default-21
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-21:4004 \
          --bind rest-api-21:8008
      "
    stop_signal: SIGKILL

  rest-api-22:
    image: hyperledger/sawtooth-rest-api:nightly
    container_name: sawtooth-rest-api-default-22
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-22:4004 \
          --bind rest-api-22:8008
      "
    stop_signal: SIGKILL

  rest-api-23:
    image: hyperledger/sawtooth-rest-api:nightly
    container_name: sawtooth-rest-api-default-23
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-23:4004 \
          --bind rest-api-23:8008
      "
    stop_signal: SIGKILL

  rest-api-24:
    image: hyperledger/sawtooth-rest-api:nightly
    container_name: sawtooth-rest-api-default-24
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-24:4004 \
          --bind rest-api-24:8008
      "
    stop_signal: SIGKILL

# -------------=== validators ===-------------

  validator-20:
    image: hyperledger/sawtooth-validator:nightly
    container_name: sawtooth-validator-default-20
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - pbft-shared:/pbft-shared
    command: |
      bash -c "
        if [ -e /pbft-shared/validators/validator-20.priv ]; then
          cp /pbft-shared/validators/validator-20.pub /etc/sawtooth/keys/validator.pub
          cp /pbft-shared/validators/validator-20.priv /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /pbft-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub /pbft-shared/validators/validator-20.pub
          cp /etc/sawtooth/keys/validator.priv /pbft-shared/validators/validator-20.priv
        fi &&
        sawtooth keygen my_key &&
        sawtooth-validator -vv \
          --endpoint tcp://validator-20:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://validator-0:8800 \
          --peers tcp://validator-1:8800 \
          --peers tcp://validator-2:8800 \
          --peers tcp://validator-3:8800 \
          --peers tcp://validator-4:8800 \
          --peers tcp://validator-5:8800 \
          --peers tcp://validator-6:8800 \
          --peers tcp://validator-7:8800 \
          --peers tcp://validator-8:8800 \
          --peers tcp://validator-9:8800 \
          --peers tcp://validator-10:8800 \
          --peers tcp://validator-11:8800 \
          --peers tcp://validator-12:8800 \
          --peers tcp://validator-13:8800 \
          --peers tcp://validator-14:8800 \
          --peers tcp://validator-15:8800 \
          --peers tcp://validator-16:8800 \
          --peers tcp://validator-17:8800 \
          --peers tcp://validator-18:8800 \
          --peers tcp://validator-19:8800
      "
  validator-21:
    image: hyperledger/sawtooth-validator:nightly
    container_name: sawtooth-validator-default-21
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - pbft-shared:/pbft-shared
    command: |
      bash -c "
        if [ -e /pbft-shared/validators/validator-21.priv ]; then
          cp /pbft-shared/validators/validator-21.pub /etc/sawtooth/keys/validator.pub
          cp /pbft-shared/validators/validator-21.priv /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /pbft-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub /pbft-shared/validators/validator-21.pub
          cp /etc/sawtooth/keys/validator.priv /pbft-shared/validators/validator-21.priv
        fi &&
        sawtooth keygen my_key &&
        sawtooth-validator -vv \
          --endpoint tcp://validator-21:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://validator-0:8800 \
          --peers tcp://validator-1:8800 \
          --peers tcp://validator-2:8800 \
          --peers tcp://validator-3:8800 \
          --peers tcp://validator-4:8800 \
          --peers tcp://validator-5:8800 \
          --peers tcp://validator-6:8800 \
          --peers tcp://validator-7:8800 \
          --peers tcp://validator-8:8800 \
          --peers tcp://validator-9:8800 \
          --peers tcp://validator-10:8800 \
          --peers tcp://validator-11:8800 \
          --peers tcp://validator-12:8800 \
          --peers tcp://validator-13:8800 \
          --peers tcp://validator-14:8800 \
          --peers tcp://validator-15:8800 \
          --peers tcp://validator-16:8800 \
          --peers tcp://validator-17:8800 \
          --peers tcp://validator-18:8800 \
          --peers tcp://validator-19:8800 \
          --peers tcp://validator-20:8800
      "
  validator-22:
    image: hyperledger/sawtooth-validator:nightly
    container_name: sawtooth-validator-default-22
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - pbft-shared:/pbft-shared
    command: |
      bash -c "
        if [ -e /pbft-shared/validators/validator-22.priv ]; then
          cp /pbft-shared/validators/validator-22.pub /etc/sawtooth/keys/validator.pub
          cp /pbft-shared/validators/validator-22.priv /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /pbft-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub /pbft-shared/validators/validator-22.pub
          cp /etc/sawtooth/keys/validator.priv /pbft-shared/validators/validator-22.priv
        fi &&
        sawtooth keygen my_key &&
        sawtooth-validator -vv \
          --endpoint tcp://validator-22:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://validator-0:8800 \
          --peers tcp://validator-1:8800 \
          --peers tcp://validator-2:8800 \
          --peers tcp://validator-3:8800 \
          --peers tcp://validator-4:8800 \
          --peers tcp://validator-5:8800 \
          --peers tcp://validator-6:8800 \
          --peers tcp://validator-7:8800 \
          --peers tcp://validator-8:8800 \
          --peers tcp://validator-9:8800 \
          --peers tcp://validator-10:8800 \
          --peers tcp://validator-11:8800 \
          --peers tcp://validator-12:8800 \
          --peers tcp://validator-13:8800 \
          --peers tcp://validator-14:8800 \
          --peers tcp://validator-15:8800 \
          --peers tcp://validator-16:8800 \
          --peers tcp://validator-17:8800 \
          --peers tcp://validator-18:8800 \
          --peers tcp://validator-19:8800 \
          --peers tcp://validator-20:8800 \
          --peers tcp://validator-21:8800
      "
  validator-23:
    image: hyperledger/sawtooth-validator:nightly
    container_name: sawtooth-validator-default-23
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - pbft-shared:/pbft-shared
    command: |
      bash -c "
        if [ -e /pbft-shared/validators/validator-23.priv ]; then
         cp /pbft-shared/validators/validator-23.pub /etc/sawtooth/keys/validator.pub
         cp /pbft-shared/validators/validator-23.priv /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
         sawadm keygen
         mkdir -p /pbft-shared/validators || true
         cp /etc/sawtooth/keys/validator.pub /pbft-shared/validators/validator-23.pub
         cp /etc/sawtooth/keys/validator.priv /pbft-shared/validators/validator-23.priv
        fi &&
        sawtooth keygen my_key &&
        sawtooth-validator -vv \
          --endpoint tcp://validator-23:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://validator-0:8800 \
          --peers tcp://validator-1:8800 \
          --peers tcp://validator-2:8800 \
          --peers tcp://validator-3:8800 \
          --peers tcp://validator-4:8800 \
          --peers tcp://validator-5:8800 \
          --peers tcp://validator-6:8800 \
          --peers tcp://validator-7:8800 \
          --peers tcp://validator-8:8800 \
          --peers tcp://validator-9:8800 \
          --peers tcp://validator-10:8800 \
          --peers tcp://validator-11:8800 \
          --peers tcp://validator-12:8800 \
          --peers tcp://validator-13:8800 \
          --peers tcp://validator-14:8800 \
          --peers tcp://validator-15:8800 \
          --peers tcp://validator-16:8800 \
          --peers tcp://validator-17:8800 \
          --peers tcp://validator-18:8800 \
          --peers tcp://validator-19:8800 \
          --peers tcp://validator-20:8800 \
          --peers tcp://validator-21:8800 \
          --peers tcp://validator-22:8800
      "
  validator-24:
    image: hyperledger/sawtooth-validator:nightly
    container_name: sawtooth-validator-default-24
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - pbft-shared:/pbft-shared
    command: |
      bash -c "
        if [ -e /pbft-shared/validators/validator-24.priv ]; then
          cp /pbft-shared/validators/validator-24.pub /etc/sawtooth/keys/validator.pub
          cp /pbft-shared/validators/validator-24.priv /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /pbft-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub /pbft-shared/validators/validator-24.pub
          cp /etc/sawtooth/keys/validator.priv /pbft-shared/validators/validator-24.priv
        fi &&
        sawtooth keygen my_key &&
        sawtooth-validator -vv \
          --endpoint tcp://validator-24:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://validator-0:8800 \
          --peers tcp://validator-1:8800 \
          --peers tcp://validator-2:8800 \
          --peers tcp://validator-3:8800 \
          --peers tcp://validator-4:8800 \
          --peers tcp://validator-5:8800 \
          --peers tcp://validator-6:8800 \
          --peers tcp://validator-7:8800 \
          --peers tcp://validator-8:8800 \
          --peers tcp://validator-9:8800 \
          --peers tcp://validator-10:8800 \
          --peers tcp://validator-11:8800 \
          --peers tcp://validator-12:8800 \
          --peers tcp://validator-13:8800 \
          --peers tcp://validator-14:8800 \
          --peers tcp://validator-15:8800 \
          --peers tcp://validator-16:8800 \
          --peers tcp://validator-17:8800 \
          --peers tcp://validator-18:8800 \
          --peers tcp://validator-19:8800 \
          --peers tcp://validator-20:8800 \
          --peers tcp://validator-21:8800 \
          --peers tcp://validator-22:8800 \
          --peers tcp://validator-23:8800
      "
# -------------=== pbft engines ===-------------

  pbft-20:
    image: hyperledger/sawtooth-pbft-engine:nightly
    container_name: sawtooth-pbft-engine-default-20
    command: pbft-engine -vv --connect tcp://validator-20:5050
    stop_signal: SIGKILL

  pbft-21:
    image: hyperledger/sawtooth-pbft-engine:nightly
    container_name: sawtooth-pbft-engine-default-21
    command: pbft-engine -vv --connect tcp://validator-21:5050
    stop_signal: SIGKILL

  pbft-22:
    image: hyperledger/sawtooth-pbft-engine:nightly
    container_name: sawtooth-pbft-engine-default-22
    command: pbft-engine -vv --connect tcp://validator-22:5050
    stop_signal: SIGKILL

  pbft-23:
    image: hyperledger/sawtooth-pbft-engine:nightly
    container_name: sawtooth-pbft-engine-default-23
    command: pbft-engine -vv --connect tcp://validator-23:5050
    stop_signal: SIGKILL

  pbft-24:
    image: hyperledger/sawtooth-pbft-engine:nightly
    container_name: sawtooth-pbft-engine-default-24
    command: pbft-engine -vv --connect tcp://validator-24:5050
    stop_signal: SIGKILL
